unbind C-b
set -g prefix C-a
bind C-a send-prefix
set -g mouse on


bind q detach-client
bind v copy-mode
bind p paste-buffer

bind d split-window -h
bind D split-window -v
bind ] select-pane -t :.+
bind [ select-pane -t :.-
